---
- name: Execute show run command
  cisco.ios.ios_command:
    commands:
      - show run
  register: config

- name: Save output
  ansible.builtin.copy:
    content: "{{ config.stdout[0] }}"
    dest: "{{ backups_destination }}"
    mode: '0600'
