---
- name: Execute show run command
  cisco.ios.ios_command:
    commands:
      - show run
  register: config

- name: Save output
  ansible.builtin.copy:
    content: "{{ config.stdout[0] }}"
    dest: "roles/ansible_network_routing/files/backups/backup_{{ inventory_hostname }}.ios"
    mode: '0600'
