---
- name: Backup routers config
  gather_facts: false
  hosts: routers
  vars_files:
    - ../files/secrets/credentials.vault
  tasks:
    - name: Execute show run command
      cisco.ios.ios_command:
        commands:
          - show run
      register: config

    - name: Save output
      ansible.builtin.copy:
        content: "{{ config.stdout[0] }}"
        dest: "../files/backups/backup_{{ inventory_hostname }}.txt"
        mode: '0600'
