---
- name: Configure interfaces and ip routes
  hosts: router-berlin
  vars_files:
    - ../files/secrets/credentials.vault
  tasks:
    - name: Replaces device configuration of listed interfaces with provided configuration
      cisco.ios.ios_interfaces:
        config:
          - name: Ethernet0/1
            description: WAN interface
            enabled: true
          - name: Ethernet0/2
            description: LAN interface
            enabled: true
        state: replaced

    - name: Replaces device configuration of listed interfaces with provided configuration
      cisco.ios.ios_l3_interfaces:
        config:
          - name: Ethernet0/1
            ipv4:
              - address: 172.16.1.100/24
          - name: Ethernet0/2
            ipv4:
              - address: 192.168.1.100/24
        state: replaced
    
    - name: Configure ip route
      cisco.ios.ios_config:
        lines: ip route 192.168.2.0 255.255.255.0 172.16.1.200


- name: Configure interfaces and ip routes
  hosts: router-paris
  vars_files:
    - ../files/secrets/credentials.vault
  tasks:
    - name: Replaces device configuration of listed interfaces with provided configuration
      cisco.ios.ios_interfaces:
        config:
          - name: Ethernet0/1
            description: WAN interface
            enabled: true
          - name: Ethernet0/2
            description: LAN interface
            enabled: true
        state: replaced

    - name: Replaces device configuration of listed interfaces with provided configuration
      cisco.ios.ios_l3_interfaces:
        config:
          - name: Ethernet0/1
            ipv4:
              - address: 172.16.1.200/24
          - name: Ethernet0/2
            ipv4:
              - address: 192.168.2.100/24
        state: replaced

    - name: Configure ip route
      cisco.ios.ios_config:
        lines: ip route 192.168.1.0 255.255.255.0 172.16.1.100