on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger NetDevOps Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://34.142.72.59"
        user: "MozkaGit"
        token: ${{ secrets.JENKINS }}
        job: "NetDevOps"
